### ISSUE TITLE
Support creating tag lists for non java files

### ISSUE THREAD

**Issue by juliangp** [mojohaus/taglist-maven-plugin#12]
I would like to be able to create tag lists for mixed java/scala projects.

Please see the pull request here: https://github.com/mojohaus/taglist-maven-plugin/pull/11

Thanks in advance!

**Comment by bmarwell** [comment]
@juliangp I gave it some thought, and I think I would like to do a more common `<includes>` and `<excludes>` approach than the sourcetypes you suggested in #11. The reason is that with your approach:

1.  it is impossible to include files without extension.
2. It is more common (nowadays)

Examples:
* https://maven.apache.org/plugins/maven-jar-plugin/examples/include-exclude.html
* https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html
* https://maven.apache.org/plugins/maven-resources-plugin/examples/include-exclude.html
* https://maven.apache.org/plugins/maven-assembly-plugin/examples/single/including-and-excluding-artifacts.html
* etc

WDYT?

If you don't have time and still need it, I can do it for a 3.1.0 release, so we can go on with the 3.0.0 release.

**Comment by juliangp** [comment]
@bmarwell I will create a PR for you today
